### ISSUE TITLE
Use an icon for current infection counts instead of tally lines

### ISSUE THREAD

**Issue by mythmon** [mythmon/pl2-card-tracker#2]
The lasers in @Osmose's eyes are getting weak, and he can't see the tally marks for infection counts. The tally lines should be replaced with an icon, probably a bug.

**Comment by Riddlerat** [comment]
Working on this here: https://github.com/mythmon/pl2-card-tracker/pull/4

**Comment by Riddlerat** [comment]
Hmm this can be marked as done/closed. I'm not able to.

**Comment by mythmon** [comment]
You should have an invite to get collaboration permissions on this PR, which would let you close things. However, you can also put `fixes #2` in a PR's description, and then the referenced issue will automatically close when the PR is merged.
